name: Bug
description: Make sure you complete the template. Otherwise, it will be closed without further explanation!
title: "[v<replace_this_with_your_uYouPlus_version>] Replace this with your title"
labels: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: _Please check the [**issues**](https://github.com/qnblackcat/uYouPlus/issues) page to see if someone has already reported the bug. **I DIDN\'T MAKE THIS CHECKBOX FOR COSMETIC.**_
    options:
    - label: I have searched the existing issues
      required: true
      
- type: checkboxes
  attributes:
    label: Have you read the FAQ?
    description: _Make sure you actually visit the [**FAQ**](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page! **I DIDN\'T MAKE THIS CHECKBOX FOR COSMETIC**_
    options:
    - label: Yes, I have read the FAQ
      required: true
    
- type: textarea
  attributes:
    label: Device information
    description: 
    value: |
        - iOS/iPadOS version: 
        - Device model: 
        - Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 
  validations:
    required: true

- type: textarea
  attributes:
    label: IPA source
    description: _How did you get the YouTube IPA?_
  validations:
    required: true

- type: textarea
  attributes:
    label: YouTube version
    description: _What is the version of the YouTube app in your IPA?_
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the issue
    description: _Please attach videos or screenshots if possible_
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: _Please attach videos or screenshots if possible_
    value: |
        1. 
        2. 
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Crash log
    description: _If the app crashes, **please provide the crash log**. It can be found in Settings > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips_
    render: shell

- type: dropdown
  attributes:
    label: Are you using the latest version of uYouPlus? If not, why?
    description: _Developers spent loads of time and effort to fix bugs & make improvements with every release. You might want to try and update to the [latest version](https://github.com/qnblackcat/uYouPlus/releases/latest) before reporting an issue._
    multiple: false
    options:
      - ✅ Yes, I'm using the latest version of uYouPlus
      - ❌ No, I'll explain with additional information below
  validations:
    required: true

- type: dropdown
  attributes:
    label: Does the issue happen with the official YouTube app from the App Store?
    description: _YouTube itself is buggy sometimes..._
    multiple: false
    options:
      - ❌ No, I cannot reproduce this issue in the official YouTube app from the App Store
      - ✅ Yes, I can reproduce this issue in the official YouTube app from the App Store 
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional information
  validations:
    required: false
